apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scylladb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:cmodk/phoenix.git'
    path: kubernetes/scylladb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: scylladb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

