apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis-port
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: "/redis.conf"
              subPath: redis.conf
              readOnly: true
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: redis-local-storage
        resources:
          requests:
            storage: 100Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 32379
      name: redis-port
  selector:
    app: redis

