platform: linux
image_resource:
  type: registry-image
  source:
    # Check out the README for oci-build-task at
    # https://github.com/concourse/oci-build-task
    repository: cmodk/oci-build-task
inputs:
- name: source-code

params:
  CONTEXT: source-code
  BUILD_ARG_arg_application: ((application))
  IMAGE_PLATFORM: linux/amd64,linux/arm64
  PUSH: type=image,name=docker.io/cmodk/((application)),push=true
  DOCKER_USERNAME: ((docker.username))
  DOCKER_PASSWORD: ((docker.password))
  DOCKER_REGISTRY: ((docker.registry))
  DOCKER_CONFIG: /root/.docker

run:
  path: build
