resources:
- name: source-code
  type: git
  source: 
    uri: git@github.com/cmodk/phoenix
    branch: master
    private_key: ((github-cmodk-key))
jobs:
- name: build
  plan:
  - get: source-code
    trigger: true
  - task: simple-task
    config:
      platform: linux
      run:
        path: echo
        args: ["Hello world"]
