resources:
- name: source-code
  type: git
  check_every: 5m
  source: 
    uri: git@github.com:cmodk/phoenix.git
    branch: ((branch))
    private_key: ((github-cmodk-key.id_rsa))
jobs:
- name: phoenix-devices
  plan:
  - get: source-code
    trigger: true
  - task: phoenix-devices
    privileged: true
    file: source-code/ci/build.yml
    vars: {application: phoenix-devices, branch: ((branch))}
  - task: phoenix-mqtt
    privileged: true
    file: source-code/ci/build.yml
    vars: {application: phoenix-mqtt, branch: ((branch))}
  - task: phoenix-events
    privileged: true
    file: source-code/ci/build.yml
    vars: {application: phoenix-events, branch: ((branch))}
  - task: phoenix-samples
    privileged: true
    file: source-code/ci/build.yml
    vars: {application: phoenix-samples, branch: ((branch))}
  - task: phoenix-helper
    privileged: true
    file: source-code/ci/build.yml
    vars: {application: phoenix-helper, branch: ((branch))}






