resources:
- name: source-code
  type: git
  check_every: 5m
  source: 
    uri: git@github.com:cmodk/phoenix.git
    branch: ((branch))
    private_key: ((github-cmodk-key.id_rsa))
jobs:
- name: phoenix-devices
  plan:
  - get: source-code
    trigger: true
  - task: create-ssh-key
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: 
          repository: busybox
      run:
        path: sh
        args: 
        - -exc
        - echo "((github-cmodk-key.id_rsa))" > ./github-key/github.id_rsa
      outputs:
        - name: github-key
  - task: phoenix-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: cmodk/oci-build-task
      inputs:
      - name: source-code
      - name: github-key
      params:
        CONTEXT: source-code
        IMAGE_PLATFORM: linux/amd64,linux/arm64
        PUSH: cmodk/phoenix:((branch))
        DOCKER_USERNAME: ((docker.username))
        DOCKER_PASSWORD: ((docker.password))
        DOCKER_REGISTRY: ((docker.registry))
        BUILDKIT_SSH: github_ssh_key=./github-key/github.id_rsa
        BUILDKIT_SECRET_github_ssh_key: ./github-key/github.id_rsa
      run:
        path: build

