apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: phoenix-mqtt
 labels:
   app: phoenix-mqtt
spec:
  serviceName: phoenix-mqtt
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-mqtt
  template:
    metadata:
      labels:
        app: phoenix-mqtt
    spec:
      containers:
      - name: phoenix-mqtt
        image: eu.gcr.io/ae101-197818/sandbox/phoenix-mqtt
        env:
        - name: PHOENIX_ENV
          value: "k8s"
        volumeMounts:
        - name: phoenix-config
          mountPath: "/usr/local/share/phoenix/config"
          readOnly: true
        - name: phoenix-certificates
          mountPath: "/usr/local/share/phoenix/certificates"
          readOnly: true
        ports:
          - containerPort: 8883
      restartPolicy: Always
      volumes:
      - name: phoenix-config
        secret:
          secretName: phoenix-config
      - name: phoenix-certificates
        secret:
          secretName: phoenix-certificates
      imagePullSecrets:
      - name:  gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-mqtt-service
spec:
  selector:
    app: phoenix-mqtt
  type: NodePort
  ports:
  - name: phoenix-mqtt-service
    protocol: TCP
    port: 8883
    targetPort: 8883
