apiVersion: apps/v1
kind: Deployment
metadata:
 name: phoenix-samples
 labels:
   app: phoenix-samples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-samples
  template:
    metadata:
      labels:
        app: phoenix-samples
    spec:
      containers:
      - name: phoenix-samples
        image: cmodk/phoenix:sandbox
        command: ["./phoenix-samples"]
        env:
        - name: PHOENIX_ENV
          value: "k8s"
        volumeMounts:
        - name: phoenix-config
          mountPath: "/usr/local/share/phoenix/config"
          readOnly: true
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
      - name: phoenix-config
        secret:
          secretName: phoenix-config

