apiVersion: apps/v1
kind: Deployment
metadata:
 name: phoenix-helper
 labels:
   app: phoenix-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-helper
  template:
    metadata:
      labels:
        app: phoenix-helper
    spec:
      containers:
      - name: phoenix-helper
        image: cmodk/phoenix-helper:sandbox
        env:
        - name: PHOENIX_ENV
          value: "k8s"
        volumeMounts:
        - name: phoenix-config
          mountPath: "/usr/local/share/phoenix/config"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: phoenix-config
        secret:
          secretName: phoenix-config

